name: Tests

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    name: "Run tests on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            script_name: 'lib/bashunit -e .env.dist'
          - os: macos-latest
            script_name: 'lib/bashunit -e .env.dist'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Install bashunit"
        run: "./install-dependencies.sh"

      - name: Run Tests
        run: ${{ matrix.script_name }}

